In [1]:
import pandas as pd
import numpy as np

In [2]:
a= pd.DataFrame({'A': ['121st', '122st', '124st', '125st', '121st', '124st', '122st', '124st', '121st'], 'Categ': ['Apple', 'Orange', 'Pears', 'Orange', 'Banana', 'Apple', 'Apple', 'Banana', 'Banana'], 'Class': ['C', 'A', 'C', 'A', 'B','B','B','A','B']})

In [3]:
a

A   Categ Class
0  121st   Apple     C
1  122st  Orange     A
2  124st   Pears     C
3  125st  Orange     A
4  121st  Banana     B
5  124st   Apple     B
6  122st   Apple     B
7  124st  Banana     A
8  121st  Banana     B

In [4]:
f = pd.get_dummies(a['Categ'])
f

Apple  Banana  Orange  Pears
0      1       0       0      0
1      0       0       1      0
2      0       0       0      1
3      0       0       1      0
4      0       1       0      0
5      1       0       0      0
6      1       0       0      0
7      0       1       0      0
8      0       1       0      0

In [5]:
a = pd.concat([a, f], axis=1)

In [6]:
a

A   Categ Class  Apple  Banana  Orange  Pears
0  121st   Apple     C      1       0       0      0
1  122st  Orange     A      0       0       1      0
2  124st   Pears     C      0       0       0      1
3  125st  Orange     A      0       0       1      0
4  121st  Banana     B      0       1       0      0
5  124st   Apple     B      1       0       0      0
6  122st   Apple     B      1       0       0      0
7  124st  Banana     A      0       1       0      0
8  121st  Banana     B      0       1       0      0

In [7]:
a.groupby(['A']).mean().reset_index() 
#basically showing us of out of all the 121st rows, what is the frequency of Apple in it
#basically it is giving the frequency of appearance of each category 

A     Apple    Banana  Orange     Pears
0  121st  0.333333  0.666667     0.0  0.000000
1  122st  0.500000  0.000000     0.5  0.000000
2  124st  0.333333  0.333333     0.0  0.333333
3  125st  0.000000  0.000000     1.0  0.000000

In [8]:
1/3

0.3333333333333333

In [9]:
a.columns

Index(['A', 'Categ', 'Class', 'Apple', 'Banana', 'Orange', 'Pears'], dtype='object')

In [10]:
index_bool = np.isin(a.columns, ['Apple', 'Banana', 'Orange', 'Pears'])

In [11]:
index_bool

array([False, False, False,  True,  True,  True,  True])

In [12]:
d = a.iloc[:, index_bool]

In [13]:
d

Apple  Banana  Orange  Pears
0      1       0       0      0
1      0       0       1      0
2      0       0       0      1
3      0       0       1      0
4      0       1       0      0
5      1       0       0      0
6      1       0       0      0
7      0       1       0      0
8      0       1       0      0

In [14]:
df = pd.DataFrame({'A': [1,2,3], 'B': [1,1,2]})

In [15]:
df

A  B
0  1  1
1  2  1
2  3  2

In [16]:
df*df #element wise multiplication

A  B
0  1  1
1  4  1
2  9  4

In [17]:
d= df['A']

In [18]:
d

0    1
1    2
2    3
Name: A, dtype: int64

In [19]:
np.dot(d.T, d)

14

In [20]:
np.dot(d.T, df)

array([14,  9], dtype=int64)

In [21]:
s = pd.DataFrame({'A': [1,2], 'B': [2,2]})

In [22]:
np.linalg.inv(s)

array([[-1. ,  1. ],
       [ 1. , -0.5]])

In [23]:
v = pd.Series([1,2], index = ['A', 'B'])

In [24]:
v

A    1
B    2
dtype: int64

In [25]:
df

A  B
0  1  1
1  2  1
2  3  2

In [26]:
df*v

A  B
0  1  2
1  2  2
2  3  4

In [27]:
#How to get column location from column name
df.columns.get_loc('A')

0

In [28]:
df.iloc[:,df.columns.get_loc('B')]

0    1
1    1
2    2
Name: B, dtype: int64

In [29]:
for x in df['A']:
    print(x)

1
2
3


In [30]:
s = df.iloc[1:]

In [31]:
s

A  B
1  2  1
2  3  2

In [32]:
s.T.reset_index()

index  1  2
0     A  2  3
1     B  1  2

In [33]:
df

A  B
0  1  1
1  2  1
2  3  2

In [34]:
g = pd.DataFrame(columns = ['A', 'B'])
for i in range(10):
    df = df.append({'A': i, 'B': i*2}, ignore_index = True)
df

A   B
0   1   1
1   2   1
2   3   2
3   0   0
4   1   2
5   2   4
6   3   6
7   4   8
8   5  10
9   6  12
10  7  14
11  8  16
12  9  18

In [38]:
Labels = np.array([1,2,3,4,5,6,7,8,8,9,10,11,12])
df.insert(0, 'Label', Labels)

In [39]:
df

Label  A   B
0       1  1   1
1       2  2   1
2       3  3   2
3       4  0   0
4       5  1   2
5       6  2   4
6       7  3   6
7       8  4   8
8       8  5  10
9       9  6  12
10     10  7  14
11     11  8  16
12     12  9  18

In [43]:
df[df['Label']==1]

Label  A  B
0      1  1  1

In [44]:
df[df['Label']==1].T

0
Label  1
A      1
B      1

In [48]:
f = df[df['Label']==1].T[1:]

In [49]:
f

0
A  1
B  1

In [53]:
f.columns = ['view']

In [54]:
f

view
A     1
B     1

In [55]:
df

Label  A   B
0       1  1   1
1       2  2   1
2       3  3   2
3       4  0   0
4       5  1   2
5       6  2   4
6       7  3   6
7       8  4   8
8       8  5  10
9       9  6  12
10     10  7  14
11     11  8  16
12     12  9  18

In [56]:
df['A'].max()

9

In [57]:
df['C'] = [0.12,0.334,0.233,0.454,0.233,0.332,0.668,0.789,0.236,0.458,0.544,0.221,0.478]

In [58]:
df

Label  A   B      C
0       1  1   1  0.120
1       2  2   1  0.334
2       3  3   2  0.233
3       4  0   0  0.454
4       5  1   2  0.233
5       6  2   4  0.332
6       7  3   6  0.668
7       8  4   8  0.789
8       8  5  10  0.236
9       9  6  12  0.458
10     10  7  14  0.544
11     11  8  16  0.221
12     12  9  18  0.478

In [60]:
df = df.round({'C':2})

In [61]:
df

Label  A   B     C
0       1  1   1  0.12
1       2  2   1  0.33
2       3  3   2  0.23
3       4  0   0  0.45
4       5  1   2  0.23
5       6  2   4  0.33
6       7  3   6  0.67
7       8  4   8  0.79
8       8  5  10  0.24
9       9  6  12  0.46
10     10  7  14  0.54
11     11  8  16  0.22
12     12  9  18  0.48

In [63]:
df.sort_values('C', ascending = False).reset_index(drop=True)

Label  A   B     C
0       8  4   8  0.79
1       7  3   6  0.67
2      10  7  14  0.54
3      12  9  18  0.48
4       9  6  12  0.46
5       4  0   0  0.45
6       2  2   1  0.33
7       6  2   4  0.33
8       8  5  10  0.24
9       3  3   2  0.23
10      5  1   2  0.23
11     11  8  16  0.22
12      1  1   1  0.12